version: '3'
services:
  app:
    container_name: tdd-book
    image: library/golang:1.8
    volumes:
      - ../:/srv/
      - ~/go:/go
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
